/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProviderPortalRouteImport } from './routes/provider-portal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated/admin/codes'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminCredentialsRouteImport } from './routes/_authenticated/admin/credentials'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin/monitoring'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin/providers'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin/submissions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as ApiPublicAccessRouteImport } from './routes/api/public/access'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'
import { Route as ApiPublicSubtitlesRouteImport } from './routes/api/public/subtitles'
import { Route as ApiPublicAdminRouteImport } from './routes/api/public/admin'
import { Route as ApiPublicIptvRouteImport } from './routes/api/public/iptv'
import { Route as ApiPublicTmdbDiscoverRouteImport } from './routes/api/public/tmdb-discover'
import { Route as ApiPublicWatchProgressRouteImport } from './routes/api/public/watch-progress'
import { Route as ApiPublicXtreamRouteImport } from './routes/api/public/xtream'
import { Route as ApiPublicXtreamPlayRouteImport } from './routes/api/public/xtream-play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderPortalRoute = ProviderPortalRouteImport.update({
  id: '/provider-portal',
  path: '/provider-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCredentialsRoute =
  AuthenticatedAdminCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicAccessRoute = ApiPublicAccessRouteImport.update({
  id: '/api/public/access',
  path: '/api/public/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubtitlesRoute = ApiPublicSubtitlesRouteImport.update({
  id: '/api/public/subtitles',
  path: '/api/public/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminRoute = ApiPublicAdminRouteImport.update({
  id: '/api/public/admin',
  path: '/api/public/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIptvRoute = ApiPublicIptvRouteImport.update({
  id: '/api/public/iptv',
  path: '/api/public/iptv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmdbDiscoverRoute = ApiPublicTmdbDiscoverRouteImport.update({
  id: '/api/public/tmdb-discover',
  path: '/api/public/tmdb-discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWatchProgressRoute = ApiPublicWatchProgressRouteImport.update({
  id: '/api/public/watch-progress',
  path: '/api/public/watch-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXtreamRoute = ApiPublicXtreamRouteImport.update({
  id: '/api/public/xtream',
  path: '/api/public/xtream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXtreamPlayRoute = ApiPublicXtreamPlayRouteImport.update({
  id: '/api/public/xtream-play',
  path: '/api/public/xtream-play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/provider-portal': typeof ProviderPortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/access': typeof ApiPublicAccessRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/subtitles': typeof ApiPublicSubtitlesRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/iptv': typeof ApiPublicIptvRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/watch-progress': typeof ApiPublicWatchProgressRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/provider-portal': typeof ProviderPortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/access': typeof ApiPublicAccessRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/subtitles': typeof ApiPublicSubtitlesRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/iptv': typeof ApiPublicIptvRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/watch-progress': typeof ApiPublicWatchProgressRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/provider-portal': typeof ProviderPortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/credentials': typeof AuthenticatedAdminCredentialsRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/access': typeof ApiPublicAccessRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/subtitles': typeof ApiPublicSubtitlesRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/iptv': typeof ApiPublicIptvRoute
  '/api/public/tmdb-discover': typeof ApiPublicTmdbDiscoverRoute
  '/api/public/watch-progress': typeof ApiPublicWatchProgressRoute
  '/api/public/xtream': typeof ApiPublicXtreamRoute
  '/api/public/xtream-play': typeof ApiPublicXtreamPlayRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/provider-portal'
    | '/reset-password'
    | '/admin'
    | '/account'
    | '/admin/codes'
    | '/admin/content'
    | '/admin/credentials'
    | '/admin/monitoring'
    | '/admin/providers'
    | '/admin/submissions'
    | '/admin/users'
    | '/api/public/access'
    | '/api/public/download'
    | '/api/public/subtitles'
    | '/api/public/admin'
    | '/api/public/iptv'
    | '/api/public/tmdb-discover'
    | '/api/public/watch-progress'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/provider-portal'
    | '/reset-password'
    | '/account'
    | '/admin/codes'
    | '/admin/content'
    | '/admin/credentials'
    | '/admin/monitoring'
    | '/admin/providers'
    | '/admin/submissions'
    | '/admin/users'
    | '/api/public/access'
    | '/api/public/download'
    | '/api/public/subtitles'
    | '/api/public/admin'
    | '/api/public/iptv'
    | '/api/public/tmdb-discover'
    | '/api/public/watch-progress'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/provider-portal'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/admin/codes'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/credentials'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/users'
    | '/api/public/access'
    | '/api/public/download'
    | '/api/public/subtitles'
    | '/api/public/admin'
    | '/api/public/iptv'
    | '/api/public/tmdb-discover'
    | '/api/public/watch-progress'
    | '/api/public/xtream'
    | '/api/public/xtream-play'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProviderPortalRoute: typeof ProviderPortalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAccessRoute: typeof ApiPublicAccessRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
  ApiPublicSubtitlesRoute: typeof ApiPublicSubtitlesRoute
  ApiPublicAdminRoute: typeof ApiPublicAdminRoute
  ApiPublicIptvRoute: typeof ApiPublicIptvRoute
  ApiPublicTmdbDiscoverRoute: typeof ApiPublicTmdbDiscoverRoute
  ApiPublicWatchProgressRoute: typeof ApiPublicWatchProgressRoute
  ApiPublicXtreamRoute: typeof ApiPublicXtreamRoute
  ApiPublicXtreamPlayRoute: typeof ApiPublicXtreamPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-portal': {
      id: '/provider-portal'
      path: '/provider-portal'
      fullPath: '/provider-portal'
      preLoaderRoute: typeof ProviderPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/codes': {
      id: '/_authenticated/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/credentials': {
      id: '/_authenticated/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthenticatedAdminCredentialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/access': {
      id: '/api/public/access'
      path: '/api/public/access'
      fullPath: '/api/public/access'
      preLoaderRoute: typeof ApiPublicAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subtitles': {
      id: '/api/public/subtitles'
      path: '/api/public/subtitles'
      fullPath: '/api/public/subtitles'
      preLoaderRoute: typeof ApiPublicSubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin': {
      id: '/api/public/admin'
      path: '/api/public/admin'
      fullPath: '/api/public/admin'
      preLoaderRoute: typeof ApiPublicAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iptv': {
      id: '/api/public/iptv'
      path: '/api/public/iptv'
      fullPath: '/api/public/iptv'
      preLoaderRoute: typeof ApiPublicIptvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmdb-discover': {
      id: '/api/public/tmdb-discover'
      path: '/api/public/tmdb-discover'
      fullPath: '/api/public/tmdb-discover'
      preLoaderRoute: typeof ApiPublicTmdbDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/watch-progress': {
      id: '/api/public/watch-progress'
      path: '/api/public/watch-progress'
      fullPath: '/api/public/watch-progress'
      preLoaderRoute: typeof ApiPublicWatchProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xtream': {
      id: '/api/public/xtream'
      path: '/api/public/xtream'
      fullPath: '/api/public/xtream'
      preLoaderRoute: typeof ApiPublicXtreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xtream-play': {
      id: '/api/public/xtream-play'
      path: '/api/public/xtream-play'
      fullPath: '/api/public/xtream-play'
      preLoaderRoute: typeof ApiPublicXtreamPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCredentialsRoute: typeof AuthenticatedAdminCredentialsRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
    AuthenticatedAdminCredentialsRoute: AuthenticatedAdminCredentialsRoute,
    AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
    AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
    AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProviderPortalRoute: ProviderPortalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAccessRoute: ApiPublicAccessRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
  ApiPublicSubtitlesRoute: ApiPublicSubtitlesRoute,
  ApiPublicAdminRoute: ApiPublicAdminRoute,
  ApiPublicIptvRoute: ApiPublicIptvRoute,
  ApiPublicTmdbDiscoverRoute: ApiPublicTmdbDiscoverRoute,
  ApiPublicWatchProgressRoute: ApiPublicWatchProgressRoute,
  ApiPublicXtreamRoute: ApiPublicXtreamRoute,
  ApiPublicXtreamPlayRoute: ApiPublicXtreamPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
